#!/usr/bin/env python3
# Keeps the string tables in step with the code.
#
# The keys are collected from every `localized(…)` call in Sources: plain literals,
# literals followed by arguments, and multi-line blocks whose lines are joined by a
# trailing backslash. Interpolations are already written as format specifiers in the
# code, so a key is the text as it stands.
#
# English is written as an identity table, so that a key which never reaches a table
# shows up as a key rather than as English that happens to read correctly. Every
# other language keeps the translations it has: they live in the `.strings` files,
# which is where a translator looks, and this only adds what is new and reports it.
#
#     make strings

import pathlib
import re
import sys

SOURCES = pathlib.Path("Sources/TesseraKit")
QUOTES = '"' * 3

SINGLE = re.compile(r'localized\(\s*"((?:[^"\\\n]|\\.)*)"\s*[,)]')
BLOCK = re.compile(
    r"localized\(\s*\n\s*" + QUOTES + r"\n(.*?)\n\s*" + QUOTES + r"\s*[,)]", re.DOTALL
)
ENTRY = re.compile(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;\s*$')

HEADER = (
    "/* The words Tessera says. Generated by `make strings` from the calls in\n"
    "   Sources; translations are edited here and kept. */\n\n"
)


def keys_in(source: str) -> list[str]:
    found = [match.group(1) for match in SINGLE.finditer(source)]

    for match in BLOCK.finditer(source):
        joined = ""

        for line in [line.strip() for line in match.group(1).split("\n")]:
            joined += line[:-1].rstrip() + " " if line.endswith("\\") else line

        found.append(joined.strip())

    return found


def existing(path: pathlib.Path) -> dict[str, str]:
    if not path.exists():
        return {}

    table = {}

    for line in path.read_text().splitlines():
        match = ENTRY.match(line.strip())

        if match:
            table[match.group(1).replace('\\"', '"')] = match.group(2).replace('\\"', '"')

    return table


def write(path: pathlib.Path, keys: list[str], table: dict[str, str]) -> None:
    lines = [
        '"%s" = "%s";' % (key.replace('"', '\\"'), table.get(key, key).replace('"', '\\"'))
        for key in keys
    ]
    path.write_text(HEADER + "\n".join(lines) + "\n")


keys = sorted({key for path in SOURCES.rglob("*.swift") for key in keys_in(path.read_text())})
untranslated: list[str] = []

for folder in sorted(SOURCES.glob("*.lproj")):
    language = folder.name.removesuffix(".lproj")
    file = folder / "Localizable.strings"
    table = {} if language == "en" else existing(file)

    if language != "en":
        untranslated += [key for key in keys if key not in table]

    write(file, keys, table)
    print(f"{language}: {len(keys)} строк")

if untranslated:
    print("\nбез перевода — они пока показываются по-английски:")

    for key in untranslated:
        print("  " + key)

    sys.exit(1)
